name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build application
        run: dotnet build "ComicWebsite.sln" --configuration Release

  test:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests (replace with actual test commands)
        run: echo "Running tests..."

  deploy:
    needs: test
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to staging (replace with actual deployment steps)
        run: echo "Deploying to staging..."
